sfdx-devops/force-app/main/default/objects/MyObject__c/MyObject__c.object-meta.xml
<CustomObject>
    <label>MyObject</label>
    <nameField>
        <label>MyObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyObjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-devops/force-app/main/default/objects/MyObject__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MyObjects</relationshipLabel>
    <relationshipName>MyObjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-devops/force-app/main/default/objects/MyObject__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>MyObjects</relationshipLabel>
    <relationshipName>MyObjects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-devops/force-app/main/default/classes/Dummy.cls
public class Dummy {
    public static final String REGEX_KEY_NAME_START = '(Foreign key external ID:)';
    public static final String REGEX_KEY_NAME_END = '(not found for field).*';
    public static final String REGEX_ENTITY_NAME = '.*(entity)';
    
    public static void run(){
        try{
            MyObject__c objeto = new MyObject__c();
            objeto.Name = 'Objeto de Teste';
            objeto.Lead__r = new Lead(ExternalId__c = 'teste2');
            objeto.Account__r = new Account(ExternalId__c = 'teste2');
            insert objeto;
        }catch(DmlException e){
            if(e.getTypeName() == 'System.DmlException'){
                for(Integer index = 0; index < e.getNumDml(); index++){
                    String keyName = e.getDmlMessage(index).replaceAll(REGEX_KEY_NAME_START, '').replaceAll(REGEX_KEY_NAME_END, '').trim();
                    String entityName = e.getDmlMessage(index).replaceAll(REGEX_ENTITY_NAME, '').trim();
                    System.debug('keyName -> ' + keyName);
                    System.debug('entityName -> ' + entityName);
                    System.debug('fieldLabel -> ' + Schema.getGlobalDescribe().get(entityName).getDescribe().getLabel());
                }
            }
        }
    }
}